# Generated by Django 5.1.2 on 2025-01-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zahtjev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_zahtjeva', models.CharField(max_length=255)),
                ('opis_zahtjeva', models.TextField()),
                ('datum_zahtjeva', models.DateField(auto_now_add=True)),
                ('obraden_zahtjev', models.BooleanField(default=False)),
            ],
        ),
    ]
