# Generated by Django 5.1.2 on 2025-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_zahtjev_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtjev',
            name='vrsta_zahtjeva',
            field=models.CharField(choices=[('kvar', 'Kvar'), ('it_problem', 'IT Problem')], default='kvar', max_length=20),
        ),
    ]
