# Generated by Django 5.1.2 on 2025-02-15 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_ulaz'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naknada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField()),
                ('aktivna_naknada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adresa', models.CharField(blank=True, max_length=255, null=True)),
                ('grad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.TextField()),
                ('adresa', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ulaz',
            name='Razlog_dolaska',
        ),
        migrations.CreateModel(
            name='PutniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec_ispune', models.DateTimeField()),
                ('datum_podnosenja', models.DateField(auto_now_add=True)),
                ('naknada_po_km', models.FloatField(null=True)),
                ('ukupna_naknada', models.FloatField(null=True)),
                ('preuzet_zahtjev', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.skola')),
            ],
        ),
        migrations.CreateModel(
            name='UnosPutniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dan', models.IntegerField()),
                ('dolazak_km', models.FloatField(null=True)),
                ('odlazak_km', models.FloatField(null=True)),
                ('prijevozno_sredstvo', models.CharField(max_length=255)),
                ('putni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unosi', to='SchoolApp.putninalog')),
            ],
        ),
        migrations.AddField(
            model_name='ulaz',
            name='razlog_dolaska',
            field=models.TextField(null=True),
        ),
    ]
