# Generated by Django 5.1.2 on 2025-02-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_naknada_profil_skola_remove_ulaz_razlog_dolaska_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='obrazlozenje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='prijevozno_sredstvo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
