# Generated by Django 5.1.2 on 2025-02-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_putninalog_obrazlozenje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putninalog',
            old_name='preuzet_zahtjev',
            new_name='zakljucan',
        ),
    ]
