# Generated by Django 5.1.2 on 2025-02-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_alter_naknada_aktivna_naknada_alter_naknada_iznos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahtjev',
            name='vrsta_zahtjeva',
            field=models.CharField(choices=[('KVAR', 'Kvar'), ('IT', 'IT Problem')], default='KVAR', max_length=20),
        ),
    ]
