# Generated by Django 5.1.2 on 2025-02-27 17:28

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0009_alter_zahtjev_vrsta_zahtjeva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naknada',
            name='iznos',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adresa',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='grad',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='mjesec_ispune',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='naknada_po_km',
            field=encrypted_model_fields.fields.EncryptedIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='obrazlozenje',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='ukupna_naknada',
            field=encrypted_model_fields.fields.EncryptedIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skola',
            name='adresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skola',
            name='naziv',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='ime_osobe',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='oib_osobe',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='prezime_osobe',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='ulaz',
            name='razlog_dolaska',
            field=encrypted_model_fields.fields.EncryptedTextField(null=True),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='dan',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='dolazak_km',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='odlazak_km',
            field=encrypted_model_fields.fields.EncryptedIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='prijevozno_sredstvo',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True),
        ),
        migrations.AlterField(
            model_name='zahtjev',
            name='opis_zahtjeva',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
