# Generated by Django 5.1.2 on 2025-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0010_alter_naknada_iznos_alter_profil_adresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naknada',
            name='iznos',
            field=models.FloatField(default=0),
        ),
    ]
