# Generated by Django 5.1.2 on 2025-03-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0011_alter_naknada_iznos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putninalog',
            name='naknada_po_km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='ukupna_naknada',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='dolazak_km',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unosputninalog',
            name='odlazak_km',
            field=models.FloatField(default=0, null=True),
        ),
    ]
