# Generated by Django 5.1.2 on 2025-03-02 20:12

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0012_alter_putninalog_naknada_po_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulaz',
            name='oib_osobe',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True, unique=True),
        ),
    ]
